name: SecurityKane Gitleaks Composite Action
description: Run gitleaks and produce a merged JSON report with metadata
inputs:
  tenant_id:
    description: Tenant identifier
    required: true
runs:
  using: composite
  steps:
    - name: Install gitleaks and jq
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y jq curl
        GITLEAKS_VERSION="${GITLEAKS_VERSION:-v8.18.4}"
        VERSION_NO_V="${GITLEAKS_VERSION#v}"
        curl -sSL -o gitleaks.tar.gz "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${VERSION_NO_V}_linux_x64.tar.gz"
        tar -xzf gitleaks.tar.gz gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks
        gitleaks version
    - name: Run gitleaks
      shell: bash
      run: |
        gitleaks detect --no-color --report-format=json --report-path gitleaks_raw.json --exit-code 0
    - name: Build merged JSON
      shell: bash
      env:
        SK_TENANT_ID: ${{ inputs.tenant_id }}
      run: |
        RAW="gitleaks_raw.json"
        if [ ! -s "$RAW" ]; then
          echo "[]" > findings.json
        else
          if jq -e . "$RAW" >/dev/null 2>&1; then
            jq 'if type=="array" then . else [] end' "$RAW" > findings.json
          else
            echo "[]" > findings.json
          fi
        fi
        GEN_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        jq -n \
          --arg tenant_id "$SK_TENANT_ID" \
          --arg repository_id "${GITHUB_REPOSITORY_ID}" \
          --arg repository_full_name "${GITHUB_REPOSITORY}" \
          --arg commit_sha "${GITHUB_SHA}" \
          --arg run_id "${GITHUB_RUN_ID}" \
          --arg generated_at "$GEN_AT" \
          --slurpfile findings findings.json \
          '{tenant_id:$tenant_id, repository_id:$repository_id, repository_full_name:$repository_full_name, commit_sha:$commit_sha, run_id:$run_id, generated_at:$generated_at, findings:$findings[0]}' > securitykane_gitleaks.json
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: securitykane-gitleaks-${{ github.run_id }}
        path: securitykane_gitleaks.json
        if-no-files-found: error

