name: SecurityKane Gitleaks Composite Action
description: Run gitleaks and produce a merged JSON report with metadata
runs:
  using: composite
  steps:
    - name: Install gitleaks and jq
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y jq curl
        GITLEAKS_VERSION="${GITLEAKS_VERSION:-v8.18.4}"
        VERSION_NO_V="${GITLEAKS_VERSION#v}"
        curl -fsSL --retry 3 --retry-all-errors --connect-timeout 10 \
          -o gitleaks.tar.gz \
          "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${VERSION_NO_V}_linux_x64.tar.gz"
        tar -xzf gitleaks.tar.gz gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks
        gitleaks version
    - name: Run gitleaks (git history)
      shell: bash
      run: |
        set -euo pipefail
        gitleaks detect --source . --no-color --report-format=json --report-path gitleaks.json --exit-code 0
        test -s gitleaks.json || echo "[]" > gitleaks.json
    - name: Merge findings
      shell: bash
      run: |
        set -euo pipefail
        jq -s 'map(if type=="array" then . else [] end) | add' gitleaks.json > findings.json
    - name: Build merged JSON
      shell: bash
      env:
        SK_TENANT_ID: ${{ env.SK_TENANT_ID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        set -euo pipefail
        GEN_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        jq -n \
          --arg tenant_id "${SK_TENANT_ID:-}" \
          --arg repository "${GITHUB_REPOSITORY}" \
          --arg commit_sha "${GITHUB_SHA}" \
          --arg run_id "${GITHUB_RUN_ID}" \
          --arg run_attempt "${GITHUB_RUN_ATTEMPT}" \
          --arg ref "${GITHUB_REF}" \
          --arg ref_name "${GITHUB_REF_NAME}" \
          --arg actor "${GITHUB_ACTOR}" \
          --arg run_url "${RUN_URL}" \
          --arg generated_at "${GEN_AT}" \
          --slurpfile findings findings.json \
          '{
            tenant_id: $tenant_id,
            repository: $repository,
            commit_sha: $commit_sha,
            run_id: $run_id,
            run_attempt: $run_attempt,
            ref: $ref,
            ref_name: $ref_name,
            actor: $actor,
            run_url: $run_url,
            generated_at: $generated_at,
            findings: $findings[0]
          }' > securitykane_gitleaks.json
    - name: Post to backend and upload to S3
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -euo pipefail

        # Check if OIDC token URL is available (requires 'id-token: write' permission)
        if [ -z "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" ]; then
          echo "ERROR: ACTIONS_ID_TOKEN_REQUEST_URL is not set."
          echo "Ensure your workflow has 'permissions: id-token: write' configured."
          echo ""
          echo "Example workflow configuration:"
          echo "  permissions:"
          echo "    id-token: write"
          echo "    contents: read"
          exit 1
        fi

        # Get OIDC token
        OIDC_TOKEN=$(curl -fsSL --retry 3 --retry-all-errors \
          -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=securitykane" \
          | jq -r '.value')

        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" = "null" ]; then
          echo "ERROR: Failed to obtain OIDC token from GitHub Actions"
          exit 1
        fi

        # Request presigned URL with retry
        for i in 1 2 3; do
          RESPONSE=$(curl -fsSL --connect-timeout 10 -X POST \
            -H "Content-Type: application/json" \
            -d "{\"token\":\"${OIDC_TOKEN}\",\"repository\":\"${GITHUB_REPOSITORY}\"}" \
            https://anamaria-deathful-ungeodetically.ngrok-free.dev/api/integrations/github/tenant-info/ 2>&1) && break
          [ $i -lt 3 ] && sleep $((2**i)) || { echo "ERROR: Failed to get presigned URL: $RESPONSE"; exit 1; }
        done

        # Validate and extract presigned URL
        S3_URL=$(echo "$RESPONSE" | jq -r '.presigned_url')
        if [ -z "$S3_URL" ] || [ "$S3_URL" = "null" ]; then
          echo "ERROR: Invalid presigned URL in response: $RESPONSE"
          exit 1
        fi

        # Upload to S3
        curl -fsSL --retry 3 --retry-all-errors --connect-timeout 30 -X PUT \
          --data-binary @securitykane_gitleaks.json \
          -H "Content-Type: application/json" \
          "${S3_URL}"
